# Week 5

## Reshaping Array using Reshape method

- Reshape array of size (m,n) to (m1,m2,n1), so that m1 x m2 x n1 = m x n

In [1]:
import numpy as np

# This is 1 x 1 array having 1 row and 1 column
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = arr.reshape(2, 3) # 2 rows and 3 columns but total number of elements is same
print(f"original array is {arr}")
print(f"Reshaped array is :\n{newarr}")

original array is [1 2 3 4 5 6]
Reshaped array is :
[[1 2 3]
 [4 5 6]]


## Flatten
- multidimensional array to one-dimensional array

In [2]:
# Flatten array
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # It is 2 x 3 array

newarr1 = arr1.flatten()

print(f"original array is {arr1}")
print(f"flattened array is {newarr1}")

original array is [[1 2 3]
 [4 5 6]]
flattened array is [1 2 3 4 5 6]


## Numpy Array indexing and slicing
### Basic Indexing
- Indexing allows us to access the individual elements or subsets of data.

In [3]:
# 1D array Indexing
arr2 = np.array([1, 2, 3, 4, 5, 6])
print(arr2.shape)

print(f"first element is arr2 is {arr[0]}") # first element
print(f"last element is {arr2[-1]}") # last element
print(f"fourth element is {arr2[3]}") # fourth element
print(" ")

# 2D array Indexing
num_2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Print dimension")
print(num_2d_array.ndim)

print("print shape")
print(num_2d_array.shape)

print("print total number of items")
print(num_2d_array.size)

print(f"first row first element: {num_2d_array[0,0]}")
print(f"last row last element: {num_2d_array[-1,-1]}")
print(f"second row third element: {num_2d_array[1,2]}")
print(f"third row second element: {num_2d_array[2,1]}")
print(" ")

# 3d array
three_d_array = np.array([
    [
        [1,2], [3,4]
    ],
    [
        [5,6], [7,8]
    ]
])
print("print dimesions")
print(three_d_array.ndim)

(6,)
first element is arr2 is 1
last element is 6
fourth element is 4
 
Print dimension
2
print shape
(3, 3)
print total number of items
9
first row first element: 1
last row last element: 9
second row third element: 6
third row second element: 8
 
print dimesions
3


## Slicing in NumPy
In Numpy, we can access the portion of an array using the slice operator:

### 1D Array Slicing
Syntax: ```array[start:stop:step]```

In [4]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# slice array from index 2-6 (6 exclusive)
print(f"slicing from 3rd element to 6th element: {arr3[2:6]}")

# slicing with steps
print(f"slicing with steps: {arr3[:6:2]}")

# negative index
print(f"Using negative indexing slicing to show every second element from end to start: {arr3[-1::-2]}")

slicing from 3rd element to 6th element: [3 4 5 6]
slicing with steps: [1 3 5]
Using negative indexing slicing to show every second element from end to start: [11  9  7  5  3  1]


### 2D array slicing
Syntax: ```array[row_start:row_stop:row_step, col_start:col_stop:col_step]```

In [8]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"printing array dimension: {array_2d.ndim}")
print(f"Original array is: {array_2d}")
# slicing first row
print(f"slicing first row: {array_2d[0:1]}")

# slicing array from first two rows and first two columns
print(f"slicing array from first two rows and first two columns: {array_2d[0:2,0:2]}")

printing array dimension: 2
Original array is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
slicing first row: [[1 2 3]]
slicing array from first two rows and first two columns: [[1 2]
 [4 5]]


## Boolean Array Indexing
Boolean array indexing allows us to select elements from an array based on conditions. This technique is helpful when we need to filter elements based on certain conditions

In [10]:
# Generating an array
arr4 = np.array([5, 10, 15, 20, 25, 30])

# Selecting elements greater than 15
print(f"print elements greater than 15: {arr4[arr4 > 15]}")

# select elements that are even
print(f"printing the elements that are even: {arr4[arr4 % 2 == 0]}")

# Modifying elements that satisfy a condition
arr4[arr4 > 15] = 99
print(arr4)

# Boolean indexing on a 2-dimensional array
arr4_2d = arr4.reshape(2, 3)
# Extracting elements greater than 4
print(arr4_2d[arr4_2d > 4])

# Setting elements greater than 4 to zero
arr4_2d[arr4_2d > 4] = 0
print(arr4_2d)



print elements greater than 15: [20 25 30]
printing the elements that are even: [10 20 30]
[ 5 10 15 99 99 99]
[ 5 10 15 99 99 99]
[[0 0 0]
 [0 0 0]]


## Numpy Arithmetic Operations

In [18]:
first_array = np.array([3, 4, 5, 6])
second_array = np.array([2, 5, 4, 3])

print(f"numpy addition: {np.add(first_array, second_array)}")
print(f"numpy substraction: {np.subtract(first_array, second_array)}")
print(f"numpy multiplication: {np.multiply(first_array, second_array)}")
print(f"numpy divide: {np.divide(first_array, second_array)}")

# array to the number
print(f"numpy power: {np.power(first_array, 2)}") # element to the power 2
print(f"numpy mod when divided by 3 to first array: {np.mod(first_array, 3)}")

# array to the second array
print(f"numpy power using second_array: {np.power(first_array, second_array)}")
print(f"numpy modulus using second power: {np.mod(first_array, second_array)}")

numpy addition: [5 9 9 9]
numpy substraction: [ 1 -1  1  3]
numpy multiplication: [ 6 20 20 18]
numpy divide: [1.5  0.8  1.25 2.  ]
numpy power: [ 9 16 25 36]
numpy mod when divided by 3 to first array: [0 1 2 0]
numpy power using second_array: [   9 1024  625  216]
numpy modulus using second power: [1 4 1 0]


## Numpy Broadcasting
- Broadcasting in Numpy allows it to perform arithmetic operations on arrays with different shapes

In [25]:
broadcast_array = np.array([1, 4, 2, 5, 9])
broadcast_array2 = np.array(4)

print(f"broadcast_array: {broadcast_array}")
print(f"broadcast_array2: {broadcast_array2}")
# multiply
multiply = np.multiply(broadcast_array, broadcast_array2)
print(f"This is element wise multiplication(not a matrix multiplication): {multiply}")



broadcast_array: [1 4 2 5 9]
broadcast_array2: 4
This is element wise multiplication(not a matrix multiplication): [ 4 16  8 20 36]


## Numpy Array Functions
Numpy has various built-in functions for various purposes:
- Array Creation Functions: ```np.array(), np.zeros(), np.ones(), np.empty()```
- Manipulation functions: ```np.reshape(), np.transpose()```
- Mathematical Functions: ```np.add(), np.substract(), np.sqrt(), np.power()```
- Statistical Functions: ```np.median(), np.mean(), np.std(), np.var()```


In [31]:
data = np.array([1, 3, 4, 5, 2, 5])
data2 = data.reshape(2,3)
print(data)
print(data2)

print(f"mean: {np.mean(data)}")
print(f"median: {np.median(data)}")
print(f"transposing using data2: {np.transpose(data2)}")
print(f"standard deviation: {np.std(data)}")
print(f"var usage: {np.var(data)}")


[1 3 4 5 2 5]
[[1 3 4]
 [5 2 5]]
mean: 3.3333333333333335
median: 3.5
transposing using data2: [[1 5]
 [3 2]
 [4 5]]
standard deviation: 1.4907119849998598
var usage: 2.2222222222222223


## Numpy Matrix Operations

In [32]:
numpy_3d_array = np.array([
    [
    [1, 2, 4], [7, 3, 9],
    ],
    [
        [3, 8, 3], [3, 1, 4]
    ],
    [
        [3, 5, 7], [4, 8, 6]
    ]
])

numpy_first_array = np.array([
    [1, 3, 4],
    [5, 3, 1],
    [3, 5, 7]
])

numpy_second_array = np.array([
    [2, 6, 7],
    [4, 4, 7],
    [2, 5, 8]
])

print(f"Matrix Multiplication: {np.matmul(numpy_first_array, numpy_second_array)}")

Matrix Multiplication: [[ 22  38  60]
 [ 24  47  64]
 [ 40  73 112]]
